### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by onine007** [yymysql/mysql-clickhouse-replication#1]
Traceback (most recent call last):
  File "mysql-clickhouse-replication.py", line 20, in <module>
    import clickhouse_driver
  File "/usr/lib64/pypy-5.0.1/site-packages/clickhouse_driver/__init__.py", line 2, in <module>
    from .client import Client
  File "/usr/lib64/pypy-5.0.1/site-packages/clickhouse_driver/client.py", line 7, in <module>
    from .connection import Connection
  File "/usr/lib64/pypy-5.0.1/site-packages/clickhouse_driver/connection.py", line 11, in <module>
    from .bufferedreader import BufferedSocketReader
ImportError: unable to load extension module '/usr/lib64/pypy-5.0.1/site-packages/clickhouse_driver/bufferedreader.pypy-41.so': /usr/lib64/pypy-5.0.1/site-packages/clickhouse_driver/bufferedreader.pypy-41.so: undefined symbol: PyByteArray_AsString

**Comment by onine007** [comment]
clickhouse-driver  的版本太新了,  pypy -m pip install  clickhouse-driver==0.0.20  就可以了
